name: thermal_preprocessing
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - aom=3.9.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - double-conversion=3.3.0
  - expat=2.6.4
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gmp=6.3.0
  - graphite2=1.3.13
  - harfbuzz=9.0.0
  - hdf5=1.14.4
  - icu=75.1
  - imath=3.1.12
  - jasper=4.2.4
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libass=0.17.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.6
  - libclang13=19.1.6
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm19=19.1.6
  - liblzma=5.6.3
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.28
  - libopencv=4.10.0
  - libopenvino=2024.5.0
  - libopenvino-auto-batch-plugin=2024.5.0
  - libopenvino-auto-plugin=2024.5.0
  - libopenvino-hetero-plugin=2024.5.0
  - libopenvino-intel-cpu-plugin=2024.5.0
  - libopenvino-intel-gpu-plugin=2024.5.0
  - libopenvino-intel-npu-plugin=2024.5.0
  - libopenvino-ir-frontend=2024.5.0
  - libopenvino-onnx-frontend=2024.5.0
  - libopenvino-paddle-frontend=2024.5.0
  - libopenvino-pytorch-frontend=2024.5.0
  - libopenvino-tensorflow-frontend=2024.5.0
  - libopenvino-tensorflow-lite-frontend=2024.5.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=17.2
  - libprotobuf=5.28.2
  - librsvg=2.58.4
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - numpy=2.2.1
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - opencv=4.10.0
  - openexr=3.3.2
  - openh264=2.5.0
  - openldap=2.6.9
  - openssl=3.4.0
  - pango=1.54.0
  - pcre2=10.44
  - pip=24.3.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pugixml=1.14
  - py-opencv=4.10.0
  - python=3.10.16
  - python_abi=3.10
  - qt6-main=6.7.3
  - readline=8.2
  - setuptools=75.6.0
  - snappy=1.2.1
  - svt-av1=2.3.0
  - tbb=2022.0.0
  - tk=8.6.13
  - tzdata=2024b
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zstd=1.5.6
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.55.3
      - matplotlib==3.10.0
      - packaging==24.2
      - pillow==11.0.0
      - pyparsing==3.2.0
      - six==1.17.0
